#' @include distance.r
#' @include origin_methods.r
NULL

#' Public transportation network datasets from LinTim software (Integrated Optimization in Public Transportation)
#' 
#' @name ptn-data
#' @rdname ptn-data
#' @docType data
#' @keywords data
#' @author Juliane Manitz and Jonas Harbering
#' @seealso \code{\link{delay-data}}
#' 
#' @source Public transportation network datasets are extracted from LinTim software (Integrated Optimization in Public Transportation; \url{http://lintim.math.uni-goettingen.de/index.php?go=data&lang=en}). Special thanks to Anita Schoebel for making the data available. 
NULL

#' \code{ptnAth} The data of the Athens Metro, consisting of 51 nodes and 52 edges. 
#' \itemize{
#' \item Vertex attributes: station name, additonal station info. 
#' \item Edge attributes: track length (in meter), minimal and maximal time required to pass the track (in minutes).
#' }
#'
#' @name ptnAth
#' @rdname ptn-data
#' @docType data
#' @keywords data
#' @source The Athens Metro data was collected by Konstantinos Gkoumas.
#' 
#' @examples
#' # Athens metro system 
#' data(ptnAth)
#' plot_ptn(ptnAth)
#'
NULL

#' \code{ptnGoe} The data of the Goettingen bus network, consisting of 257 nodes and 548 edges. \itemize{
#' \item Vertex attributes: station name. 
#' \item Edge attributes:  track length (in meter), minimal and maximal time required to pass the track (in minutes).
#' }
#'
#' @name ptnGoe
#' @rdname ptn-data
#' @docType data
#' @keywords data
#' @source The Goettingen bus network data was collected by Barbara Michalski.
#' 
#' @examples
#' # Goettingen bus system 
#' data(ptnGoe)
#' plot_ptn(ptnGoe)
#'
NULL

#' Delay propagation data examples simulated by LinTim software
#' 
#' @name delay-data
#' @rdname delay-data
#' @docType data
#' @keywords data
#' @author Jonas Harbering
#' @seealso \code{\link{ptn-data}}
#' 
#' @references Manitz, J., J. Harbering, M. Schmidt, T. Kneib, and A. Schoebel (2017): Source Estimation for Propagation Processes on Complex Networks with an Application to Delays in Public Transportation Systems. Journal of Royal Statistical Society C (Applied Statistics), 66: 521-536.
#' 
#' @source Public transportation network datasets are generated by LinTim software (Integrated Optimization in Public Transportation; \url{http://lintim.math.uni-goettingen.de/index.php?go=data&lang=en}). 
NULL

#' \code{delayAth} Delay propagation data generated on the Athens metro network by LinTim software
#' 
#' @name delayAth
#' @rdname delay-data
#' @docType data
#' @keywords data
#' 
#' @details \code{delayAth} Delay data on the Athens metro network. Propagation simulation under consideration of secruity distances and fixed-waiting time delay management. 'data.frame' with 510 observations (10 sequential time pictures for delay spreading pattern from 51 stations) of 53 variables (\code{k0} true source, \code{time}, delays at 51 stations).
#'
#' @import igraph 
#'
#' @examples
#' \dontrun{ 
#' # compute effective distance
#' data(ptnAth)
#' athnet <- igraph::as_adjacency_matrix(ptnAth, sparse=FALSE)
#' p <- athnet/rowSums(athnet)
#' eff <- eff_dist(p)
#' # apply source estimation
#' if (requireNamespace("aplyr", quietly = TRUE)) {
#' data(delayAth)
#' res <- alply(.data=delayAth[,-c(1:2)], .margins=1, .fun=origin_edm, distance=eff,
#'              silent=TRUE, .progress='text')
#' perfAth <- ldply(Map(performance, x = res, start = as.list(delayAth$k0),  
#'                      list(graph = ptnAth)))
#' }
#' } 
NULL

#' \code{delayGoe} Delay propagation data generated on the Goettingen bus system by LinTim software
#' 
#' @name delayGoe
#' @rdname delay-data
#' @docType data
#' @keywords data
#' 
#' @details \code{delayGoe} Delay data on the directed Goettingen bus system. Progation simulation under consideration of secruity distances and fixed-waiting time delay management. 'data.frame' with 2570 observations (10 sequential time pictures for delay spreading pattern from 257 stations) of 259 variables (\code{k0} true source, \code{time}, delays at 257 stations).
#'
#' @import igraph 
#'
#' @examples
#' \dontrun{ 
#' # compute effective distance
#' data(ptnGoe)
#' goenet <- igraph::as_adjacency_matrix(ptnGoe, sparse=FALSE)
#' p <- goenet/rowSums(goenet)
#' eff <- eff_dist(p)
#' # apply source estimation
#' if (requireNamespace("aplyr", quietly = TRUE)) {
#' data(delayGoe)
#' res <- alply(.data=delayGoe[,-c(1:2)], .margins=1, .fun=origin_edm, distance=eff,
#'              silent=TRUE, .progress='text')
#' perfGoe <- ldply(Map(performance, x = res, start = as.list(delayGoe$k0), 
#'                      list(graph = ptnGoe)))
#' }
#' } 
NULL

#' \code{envirparaList} Environment parameters List for KwaZulu-Natal
#' 
#' @name envirparaList
#' @rdname envirparaList
#' @docType data
#' @keywords data
#' 
#' @details \code{envirparaList} Environment parameters List for KwaZulu-Natal
#'    beta_max: maximum contact rate (day^-1)
#'    beta: contact rate (day^-1) for each node, length 851
#'    theta_max: maximum contamination rate
#'    theta: contamination rate for each node, length 851
#'    humanmob.mass: An 851-by-851 matrix, where each row contains the probabilities a person travels from the given city (by Row Index) to another city (by Column Index).
#'      For example, the first row represents the probabilities that a person travels from City 1 to the other 850 cities.
#'    lati.long.851: a 851-by-2 matrix, of which the 1st column is longitude and the 2nd column is latitude, for each city
#'    newcases.per.day: new cases per day per node, 851(number of nodes)-by-1312(number of days)
#'    no_toilet_access: probability of no toilet access for each node (length 851 vector)
#'    no_water_access: probability of no water access for each node (length 851 vector)
#'    popu: population for each node (length 851 vector)
#'    R0_max: maximum reproduction number
#'    R0: maximum reproduction number for each node (length 851 vector)
#'    alpha: cholera induced mortality rate (day^-1)
#'    gamma: rate at which people recover from cholera (day^-1)
#'    incidence.threshold: The threshold value applied to the percent of infected individuals in a city population, used to declare whether or not the city is infected.
#'    mu: population natality and mortality rate (day^-1)
#'    mu_B: death rate of V.cholerae in the aquatic environment (day^-1)
#'    rho: immunity loss rate (day^-1)
#'    sigma: symptomatic ratio, i.e., fraction of infected people that develop symptoms and are infective. (The remaining fraction enters directly the recovered compartment.)
#'
#' @examples
#' data(envirparaList)
#' y0 <- initial_condition_sib_model(envirparaList$popu, envirparaList$sigma, 
#'   envirparaList$mu_B, envirparaList$theta, c(428))
NULL



